name: Validate TypeScript

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Validate TypeScript
        run: npm test
      - name: Validate individual .d.ts files
        run: |
          set -e
          for i in index.d.ts types/*.d.ts; do
            echo "Validating $i"
            npx tsc "$i" --target es6 --noEmit
          done
